### ISSUE TITLE
Fails to run kameris on windows

### ISSUE THREAD

**Issue by mavino** [stephensolis/modmap-toolkit#2]
```
python -V
Python 3.7.1

C:\Users\MDGA\Downloads\kameris-master\kameris-master>python kameris.py classify
 hiv-1mlp C:\Users\MDGA\Downloads\hiv1-genomes
ERROR    an unexpected error occurred: ModuleNotFoundError: No module named 'bac
kports'
ERROR    ***if you believe this is a bug, please report it at https://github.com
/stephensolis/kameris/issues and include ALL the following text:***
Traceback (most recent call last):
  File "C:\Users\MDGA\Downloads\kameris-master\kameris-master\kameris\__main__.p
y", line 39, in main
    '.subcommands.' + args.module_name, 'kameris'
  File "C:\Users\MDGA\AppData\Local\Programs\Python\Python37-32\lib\importlib\__
init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\MDGA\Downloads\kameris-master\kameris-master\kameris\subcommand
s\classify.py", line 4, in <module>
    from backports import tempfile
ModuleNotFoundError: No module named 'backports'
```

**Comment by stephensolis** [comment]
You need to follow the installation instructions: https://github.com/stephensolis/kameris#installing before running the software.

**Comment by mavino** [comment]
already followed installation instructions but not able to run it on windows

**Comment by stephensolis** [comment]
Try `python -m pip install kameris`

**Comment by mavino** [comment]
```
C:\Users\MDGA>python -m pip install kameris
Traceback (most recent call last):
  File "C:\Users\MDGA\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", l
ine 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\MDGA\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", l
ine 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\MDGA\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", l
ine 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\MDGA\AppData\Local\Programs\Python\Python37-32\lib\site-package
s\pip\__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "C:\Users\MDGA\AppData\Local\Programs\Python\Python37-32\lib\site-package
s\pip\utils\__init__.py", line 23, in <module>
    from pip._vendor import pkg_resources
  File "C:\Users\MDGA\AppData\Local\Programs\Python\Python37-32\lib\site-package
s\pip\_vendor\pkg_resources\__init__.py", line 1712, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader
'
```

**Comment by stephensolis** [comment]
I think your Python installation is corrupt, try re-installing.
This is not a Kameris issue.
