### ISSUE TITLE
kameris run-job problem

### ISSUE THREAD

**Issue by mavino** [stephensolis/modmap-toolkit#5]
```
kameris run-job https://raw.githubusercontent.com/stephensolis/kameris/master/demo/hiv1-lanl.yml https://raw.githubusercontent.com/stephensolis/kameris/master/demo/settings.yml
INFO     retrieving 'https://raw.githubusercontent.com/stephensolis/kameris/master/demo/hiv1-lanl.yml'
INFO     retrieving 'https://raw.githubusercontent.com/stephensolis/kameris/master/demo/settings.yml'
INFO     *** started experiment 'subtype-k=5' (1/2)
INFO     retrieving 'https://raw.githubusercontent.com/stephensolis/kameris-experiments/master/files.yml'
INFO     started downloading 'https://raw.githubusercontent.com/stephensolis/kameris-experiments/master/metadata/hiv1-lanl-whole.json'
ERROR    an unexpected error occurred: AttributeError: __exit__
ERROR    ***if you believe this is a bug, please report it at https://github.com/stephensolis/kameris/issues and include ALL the following text:***
Traceback (most recent call last):
  File "/Users/Lab/anaconda/lib/python2.7/site-packages/kameris/__main__.py", line 41, in main
    run_module.run(args)
  File "/Users/Lab/anaconda/lib/python2.7/site-packages/kameris/subcommands/run_job.py", line 242, in run
    args.urls_file, metadata_name)
  File "/Users/Lab/anaconda/lib/python2.7/site-packages/kameris/subcommands/run_job.py", line 168, in load_metadata
    file_path
  File "/Users/Lab/anaconda/lib/python2.7/site-packages/kameris/utils/download_utils.py", line 37, in download_file
    with requests.get(url, stream=True) as r:
AttributeError: __exit__
```

**Comment by stephensolis** [comment]
Can you try `pip install --upgrade requests`?
